# Generated by Django 4.1.6 on 2023-03-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business_user_accounts",
            name="password",
            field=models.CharField(default="password", max_length=200),
        ),
        migrations.AddField(
            model_name="user_accounts",
            name="password",
            field=models.CharField(default="password", max_length=200),
        ),
    ]
